### ISSUE TITLE
betRewardType を ITEM に、enableTemporaryInventory を false にすると、勝利時にNullPointerExceptionが発生する。

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/ReversiLab#11]
betRewardType を ITEM に、enableTemporaryInventory を false に設定してゲームを開始し、
勝利して報酬が支払われるときに、NullPointerExceptionが発生して元いた場所への転送が行われない。

ログは下記の通り。

<pre>
[22:55:38] [Server thread/INFO]: [Rev]ucchy 対 CPU(NORMAL) のリバーシ対戦が終了しました！
49 対 15 で、ucchyさんの勝利です！
[22:55:38] [Server thread/WARN]: [ReversiLab] Task #154 for ReversiLab v1.0.1 generated an exception
java.lang.NullPointerException
    at org.bitbucket.ucchy.reversi.game.SingleGameSession.runEnd(SingleGameSession.java:401) ~[?:?]
    at org.bitbucket.ucchy.reversi.game.SingleGameSession$3.run(SingleGameSession.java:305) ~[?:?]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-e0e1771-5e5cf84]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
</pre>

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
